name: Docker Image CI
on:
  push:
    branches:
    - main

jobs:
  maven:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'
        
    - name: Check Java Version
      run: java -version
       
    - name: Build with Maven
      run: mvn -B verify --file pom.xml

    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  docker:

    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Download artifact from maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app
    - name: Logging into docker
      run: docker login ghcr.io -u attilaszegedi -p ${{ github.token }}

    - name: Build docker
      run: docker build . --file Dockerfile --tag ghcr.io/attilaszegedi/cloud-native-db-demo:springboot3

    - name: Publish docker
      run: docker push ghcr.io/attilaszegedi/cloud-native-db-demo:springboot3
